---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: latest httpd version installed
    yum:
      name: httpd
      state: latest
  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest
  - name: httpd enabled and running
    service:
      name: httpd
      enabled: true
      state: started
  - name: firewalld enabled and running
    service: 
      name: firewalld
      enabled: true
      state: started
  - name: firewlld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
    # notify:
    #   - restart firewalld
  - name: restart firewalld
    service:  
      name: firewalld
      state: restarted

#- name: set message of the day
- hosts: all
  user: root
  become: true
  vars:
    system_owner: pradeep@example.com
  tasks:
   - template: 
       src: motd.j2
       dest: /etc/motd
       owner: root
       group: root
       mode: 0644

- hosts: all
  user: root
  become: true
  tasks:
   - template: 
       src: homepage.j2
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644     