Vagrant.configure("2") do |config|
 config.vm.define "test1.example.com" do |test1|
 test1.vm.box="centos/7"
 test1.vm.hostname="test1.example.com"
 test1.vm.network "forwarded_port",guest:80,host:8000
 test1.vm.network :private_network, ip:"10.0.0.10"
 end
 config.vm.define "test2.example.com" do |test2|
 test2.vm.box="centos/7"
 test2.vm.hostname="test2.example.com"
 test2.vm.network "forwarded_port",guest:80,host:8001
 test2.vm.network :private_network, ip:"10.0.0.11"
 end
 config.vm.provision "ansible" do |ansible|
  ansible.playbook='playbook.yml'
 end
end

